"""Serves files generated by tools (currently: PDF itineraries from
app/tools/pdf_tool.py). Filenames are server-generated UUIDs, so there's
no path-traversal risk from user input, but we still resolve-and-check as
defense in depth."""
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse

from app.api.deps import get_current_user
from app.db.models import User
from app.tools.pdf_tool import GENERATED_DIR

router = APIRouter(prefix="/files", tags=["Files"])


@router.get("/{filename}")
def download_file(filename: str, _user: User = Depends(get_current_user)):
    filepath = (GENERATED_DIR / filename).resolve()
    if GENERATED_DIR.resolve() not in filepath.parents or not filepath.exists():
        raise HTTPException(status_code=404, detail="File not found")
    return FileResponse(filepath, media_type="application/pdf", filename=filename)
