from typing import TypedDict, List, Dict, Any, Optional


class AgentState(TypedDict):
    # Session
    session_id: str

    # Original user message
    user_input: str

    # Chat history
    conversation_history: List[Dict[str, str]]

    # Optional authenticated user
    user_id: Optional[str]

    # Router output
    task_type: str

    # Planner output
    execution_plan: List[str]

    # Currently executing agent
    current_agent: str

    # Supervisor output
    supervisor_tasks: List[Dict[str, str]]

    # Shared structured travel information
    travel: Optional[Dict[str, Any]]

    # Outputs from every agent
    agent_outputs: Dict[str, Any]

    # Execution Timeline
    execution_log: List[Dict[str, Any]]

    # Final response generated by ResponseAgent
    final_response: Any